In [1]:
import pandas as pd
pd.set_option("display.max_columns", None)

from tqdm import tqdm
tqdm.pandas()

import numpy as np

In [2]:
india = pd.read_csv("India_riskliteracy_dataset_above median_2024.csv")
india.drop(["Unnamed: 1", "#.1"], axis = 1).rename({"#":"responseid"}, axis = 1)

,responseid,Please indicate your Gender.,Please mark your age (in years),What is currently your highest Education?,Please state your current occupation.,How do you describe your willingness to take financial risk in general?,"Given the number of years that you have held various investments and the amount of investing you might have done, what degree of investment experience in the stock market do you have?","If an expert tries to worry or scare me, i.e. a financial advisor about my financial situation, I choose another expert.",I only buy a financial product I understand.,I trust doctors.,"When I want to buy a bigger item like a refrigerator or an expensive item of clothing, I wait a month to see whether I still want it and only buy it then.",I always keep in mind that everything I do on the web could be used to my disadvantage.,"In my household, we/I spend:","In my household, we/I",_Distribution 1_\n\nHow risky do you perceive the investment to be?,_Distribution 2_\n\nHow risky do you perceive the investment to be?,_Distribution 3_\n\nHow risky do you perceive the investment to be?,_Distribution 4_\n\nHow risky do you perceive the investment to be?,_Distribution 5_\n\nHow risky do you perceive the investment to be?,Distribution 6\n\nHow risky do you perceive the investment to be?,Distribution 7\n\nHow risky do you perceive the investment to be?,Distribution 8\n\nHow risky do you perceive the investment to be?,*Mumbai * A = 9 out of 10000 *OR * B = 1 out of 1000,*Bengaluru * A = 0.7% *OR * B = 0.099%,*Kolkata * A = 0.61% *OR * B = 6 out of 10000,HIV test,Fingerprint,DNA test,Cancer screening test,Professional horoscope,A study estimates that eating 100g chocolate everyday increases the risk of obesity by 20%. Which of the following statements is true?,There is an official prediction that the national stock market will grow 2% annually over the next 5 years. This means thatâ€¦,Imagine you are told that the price of the stock Soya Ruchi increases from INR 60 to INR 120 after the company merger. What does this mean?,It is predicted that Indigo Bank has 30% chance of default next year. Which of the following alternatives is the most appropriate interpretation of the statement?,"The probability that the economy will go into a recession this year is 30%. If the economy goes into recession, the probability that the stock market will decrease is 80%. If the economy does not go into a recession, the probability that the stock market will decrease is 23%. What is the probability that the economy goes into recession given that the stock market decreased?",A new policy intervention increases the number of people who are employed by 20%. This statistic implies that the intervention increases the number of people who are employed from:,"Imagine you are told that a new medication increases the number of people who recover from a disease from 2 out of 1,000 to 4 out of 1,000. This implies:","Imagine that we flip a fair coin 1,000 times. What is your best guess about how many times the coin will come up heads in 1,000 flips? \n\n\_\_\_\_\_\_ times out of 1,000.","In the Bingo Lottery, the chance of winning a $10 prize is 1%. What is your best guess about how many people will win a $10 prize if 1,000 people each buy a single ticket for Bingo Lottery?\n\n\_\_\_\_\_\_ person(s) out of 1,000.","In a sweepstakes, the chance of winning a car is 1 in 1,000. What percentage of tickets for the sweepstakes wins a car?\n\n\_\_\_\_\_ % of tickets","About 10 out of 1,000 children develop Down syndrome. In a Down syndrome test, 9 out of these 10 children with Down syndrome tested positive. Out of the 990 children without Down syndrome 50 nevertheless tested positive. Among those women with a positive test result concerning their child how many actually have a child with Down syndrome? [Select one response only]","Approximately what percentage (%) of people who die from cancer die from colon cancer, breast cancer, and prostate cancer taken together?",The following figure shows the number of men and women among a group of smartphone users. The total number of circles is 100. \n\nHow many more men than women are there among the 100 people using a smartphone?,"In a magazine you see two advertisements, one on page 5 and another on page 12. Each is for a different drug for treating heart disease, and each includes a graph showing the effectiveness of the drug compared to a placebo (sugar pill).\n\nCompared to the placebo, which treatment leads to a larger decrease in the percentage of patients who die?",Please indicate your approximate annual personal income from all sources for last year,"Please provide a rough guess (in Indian Rupees) of the worth of your household's assets. Please do not forget to correct it for your debts, such as a mortgage or any loans you might have.",uid,Response Type,Start Date (UTC),Stage Date (UTC),Submit Date (UTC),Network ID,LTA,q8_2_1,q8_2_2,q8_2_3,q8_2_4,q8_2_5,q8_3,q8_4,q8_5berlin_1,q8_5london_1,q8_5paris_1,q8_6,q8_7,q9_1_1,q9_2_1,q9_3,q10_1_1,q10_2_1,q10_3_1,q10_4,certainty1,certainty2,certainty3,certainty4,certainty5,uncertainty1,uncertainty2,numeracy1,numeracy2,numeracy3,numeracy4,numeracy5,graph1,graph2,graph3,riskcalculation1,riskcalculation2,riskcalculation3,riskcalculation4,Certainty score_5,Uncertainty score_5,Number Comprehension score_5,Graph Comprehension score_5,Calculation score_4,Total Score_19
0,00dn8csjzlekx6gzhrcv00dn8csj32tz,Male,25 - 35,Under Graduate,"Investment Professional, i.e. stock broker/tra...",7,10,Completely,Just about,Completely,Completely,Just about,"all or more than the household income, even th...","have an emergency fund, and spend as it feels ...",7,7,7,6,6,6,6,7,A,B,A,Yes,Yes,Yes,Yes,Yes,"The lower the quality of the study, the more l...",the growth rate will be 0.4% on average each year,the stock price increased by 50%,30% of the banks customers will default next year,30%,it is not possible to determine which of the a...,The medication increases recovery by 50%,30,20,30,9 out of 10,40,60,They are equal,"5,00,000 - 15,00,000",50000,MX9oX1724844773oYI,completed,2024-08-28 11:35:35,NaN,2024-08-28 12:02:05,f30fdd629e,18.402778,1,1,1,1,1,1,1,1,2,1,2,4,40,60,3,30,20,30,2,0,0,0,0,0,1,0,0,0,1,0,1,0,0,1,0,0,0,0,0,1,2,1,0,4
1,00ujdxbfoya0donu8r00ujcjdkojc99x,Female,25 - 35,Under Graduate,Employee/Consultant in Other than the Finance ...,7,8,Completely,Completely,Completely,Moderately,Moderately,less than half of the household income and sav...,"write down budget and spending, and have an em...",2,1,1,1,0,2,0,0,B,B,A,Yes,Yes,Yes,Yes,No,"The higher the quality of the study, the more ...",the growth rate over five years will be betwee...,the stock price increased by 50%,The bank will default on 30% of repayments in ...,50%,"100 in 10,000 people prior to the intervention...",The medication increases recovery by 50%,500,100,1,59 out of 1000,50,10,They are equal,"&lt; 5,00,000",1500000,MXic21725178744djB,completed,2024-09-01 08:23:04,NaN,2024-09-01 09:24:44,1c1d51349c,42.824074,1,1,1,1,2,2,3,2,2,1,2,2,50,10,3,500,100,1,3,0,0,0,0,1,0,0,1,0,1,0,0,0,0,1,1,0,0,0,1,0,2,1,1,5
2,01ro2iftnum5v4cn01r03c75aa24emhq,Female,18 - 25,Under Graduate,Student,5,8,Just about,Completely,Completely,Completely,Just about,more than half of the household income and sav...,"write down budget and spending, and have an em...",6,6,2,6,6,6,2,4,A,B,B,Yes,Yes,No,Yes,Yes,"The lower the quality of the study, the more l...",the growth rate over five years will be exactl...,an answer is not possible based on the informa...,Banks similar to Indigo will default 30% of th...,50%,70 in 100 people prior to the intervention to ...,The medication increases recovery by 100%,46,100,99,59 out of 1000,79,40,Hertinol,"5,00,000 - 15,00,000",500000,MX7wI1724844822zNm,completed,2024-08-28 11:36:50,NaN,2024-08-28 11:51:07,81a8a6836a,9.918981,1,1,2,1,1,1,2,1,2,2,1,3,79,40,2,46,100,99,3,0,0,1,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,1,1,1,0,0,3
3,022xoawhrghfhv4a1g022xmz7hb0m41f,Female,46 - 55,Under Graduate,Entrepreneur or Own Business,5,4,Somewhat,Somewhat,Moderately,Just about,Somewhat,"all or more than the household income, even th...","spend as it feel right, and do not have an eme...",4,4,4,4,4,4,4,4,B,A,B,Yes,Yes,Yes,No,No,"The lower the quality of the study, the more l...",the growth rate will be 0.4% on average each year,the stock price increased by 60%,30% of the banks customers will default next year,80%,5 in 100 people prior to the intervention to 6...,The medication increases recovery by 2%,500,1,1,59 out of 1000,17,65,They are equal,"&lt; 5,00,000",15000000,MXFDH1725178659xRn,completed,2024-09-01 08:21:14,NaN,2024-09-01 08:33:49,fbd8962401,8.738426,1,1,1,2,2,1,1,2,1,2,3,1,17,65,3,500,1,1,3,0,0,0,1,1,1,0,1,1,0,0,0,0,0,1,1,0,0,0,2,1,2,1,1,7
4,02pxtdbyibecqqfvwlw02pxwfbane9zd,Female,46 - 55,Post Graduate,Employee/Consultant in Other than the Finance ...,6,10,Not at all,Completely,Completely,Completely,Moderately,"all or more than the household income, even th...","have an emergency fund, and spend as it feels ...",5,5,6,5,7,5,0,5,B,A,A,Yes,Yes,Yes,No,Yes,"The higher the quality of the study, the more ...",it is not possible to predict the growth rate ...,an answer is not possible based on the informa...,30% of the banks customers will default next year,30%,5 in 100 people prior to the intervention to 6...,None of the above is implied.,1000,1,100,9 out of 10,20,20,Canâ€™t say,"5,00,000 - 15,00,000",3000000,MXIpM1724844742xet,completed,2024-08-28 11:35:05,NaN,2024-08-28 11:48:47,e8b668d11b,9.513889,1,1,1,2,1,2,4,2,1,1,4,1,20,20,4,1000,1,100,2,0,0,0,1,0,0,1,1,1,1,0,0,0,1,0,0,0,0,0,1,1,3,1,0,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
638,zeoufbqlngfunzzeoymhtj2sp5cw6lur,Male,25 - 35,Post Graduate,"Investment Professional, i.e. stock broker/tra...",3,8,Not at all,Somewhat,Somewhat,Moderately,Somewhat,less than half of the household income and sav...,"spend as it feel right, and do not have an eme...",3,4,4,3,6,6,3,4,B,A,A,No,Yes,No,No,No,"The higher the quality of the study, the more ...",the growth rate over five years will be exactl...,the stock price increased by 100%,Banks similar to Indigo will default 30% of th...,50%,70 in 100 people prior to the intervention to ...,The medication increases recovery by 100%,500,100,1,59 out of 1000,50,40,Crosicol,"&lt; 5,00,000",50000,MXFoD1725258821KAh,completed,2024-09-02 06:36:01,NaN,2024-09-02 06:46:38,c31fa70c8d,7.372685,2,1,2,2,2,2,2,2,1,1,1,3,50,40,1,500,100,1,3,1,0,1,1,1,0,0,1,1,1,1,0,0,0,0,1,0,0,0,4,0,4,0,1,9
639,zfemo30rg0ekva18x1kjwzfemo2wpg2p,Male,36 - 45,Ph.D. or higher,Employee/Consultant in Other than the Finance ...,6,8,Not at all,Moderately,Just about,Not at all,Not at all,less than half of the household income and sav...,"have an emergency fund, and spend as it feels ...",3,1,4,2,0,5,0,2,B,A,A,No,Yes,Yes,No,No,"Irrespective of the quality of the study, futu...",the growth rate over five years will be betwee...,the stock price increased by 100%,30% of central bankers think that Indigo Bank ...,30%,"100 in 10,000 people prior to the intervention...",The medication increases recovery by 100%,500,10,1,59 out of 1000,25,20,Canâ€™t say,"15,00,001 - 25,00,000",8500000,MXUxt1725260651heG,completed,2024-09-02 07:08:18,NaN,2024-09-02 07:23:09,fbb956cffc,10.312500,2,1,1,2,2,4,3,2,1,1,1,2,25,20,4,500,10,1,3,1,0,0,1,1,0,0,1,1,1,1,0,1,1,0,1,1,0,0,3,0,4,2,2,11
640,znqvw4t38br3072znqvwvjsgb6wvj7nt,Female,36 - 45,Post Graduate,Entrepreneur or Own Business,5,5,Somewhat,Completely,Just about,Moderately,Somewhat,less than half of the household income and sav...,"spend as it feel right, and do not have an eme...",0,0,0,1,0,0,0,0,B,B,B,Yes,Yes,Yes,No,No,"Irrespective of the quality of the study, futu...",it is not possible to predict the growth rate ...,the stock price increased by 50%,30% of the banks customers will default next year,80%,it is not possible to determine which of the a...,The medication increases recovery by 2%,500,10,1,9 out of 59,25,20,Hertinol,"5,00,000 - 15,00,000",2000000,MXd921725259652XDJ,completed,2024-09-02 06:49:56,NaN,2024-09-02 07:17:20,1964f49e1c,19.027778,1,1,1,2,2,3,4,2,2,2,3,4,25,20,2,500,10,1,1,0,0,0,1,1,0,1,1,0,0,0,1,1,1,0,1,1,0,1,2,1,2,2,3,10
641,zstpq23h1x3ilab8s8vsrbkw8t4zstpq,Male,18 - 25,Under Graduate,Entrepreneur or Own Business,6,9,Completely,Completely,Moderately,Completely,Moderately,"all or more than our household income, because...","have an emergency fund, and spend as it feels ...",6,3,7,1,2,7,7,3,A,A,B,No,Yes,Yes,No,No,"The higher the quality of the study, the more ...",the growth rate over five years will be betwee...,the stock price increased by 60%,Banks similar to Indigo will default 30% of th...,80%,5 in 100 people prior to the intervention to 6...,None of the above is implied.,750,10,1,59 out of 1000,50,10,They are equal,"5,00,000 - 15,00,000",60000000,MXfmg1725259705Fkj,completed,2024-09-02 06:49:52,NaN,2024-09-02 07:01:04,03aa77ec48,7.777778,2,1,1,2,2,2,3,1,1,2,4,1,50,10,3,750,10,1,3,1,0,0,1,1,0,0,0,1,0,0,0,0,0,1,0,1,0,0,3,0,1,1,1,6
642,ztfdlcbiyo1xco3ztfdl4ozqpte2q3m9,Male,25 - 35,Post Graduate,Entrepreneur or Own Business,6,7,Somewhat,Just about,Completely,Moderately,Somewhat,more than half of the household income and sav...,"spend as it feel right, and do not have an eme...",6,0,2,5,3,7,0,4,B,A,A,No,Yes,Yes,Yes,Yes,"The higher the quality of the study, the more ...",it is not possible to predict the growth rate ...,the stock price increased by 100%,30% of central bankers think that Indigo Bank ...,80%,5 in 100 people prior to the intervention to 6...,The medication increases recovery by 2%,500,10,1,59 out of 1000,25,60,Canâ€™t say,"15,00,001 - 25,00,000",5000000,MXjp51725955476hMt,completed,2024-09-10 08:06:34,NaN,2024-09-10 08:16:35,f68294192e,6.956019,2,1,1,1,1,2,4,2,1,1,3,1,25,60,4,500,10,1,3,1,0,0,0,0,0,1,1,1,1,0,0,1,0,0,1,1,0,0,1,1,3,1,2,8

In [3]:
otherCountries = pd.read_csv("5country_riskliteracy_dataset_2024.csv")
otherCountries = otherCountries.drop(["Unnamed: 1", "responseid.1"], axis = 1)
otherCountries

,responseid,q8_2_1,q8_2_2,q8_2_3,q8_2_4,q8_2_5,q8_3,q8_4,q8_5berlin_1,q8_5london_1,q8_5paris_1,q8_6,q8_7,q9_1_1,q9_2_1,q9_3,q10_1_1,q10_2_1,q10_3_1,q10_4,certainty1,certainty2,certainty3,certainty4,certainty5,uncertainty1,uncertainty2,numeracy1,numeracy2,numeracy3,numeracy4,numeracy5,graph1,graph2,graph3,riskcalculation1,riskcalculation2,riskcalculation3,riskcalculation4,Certainty score_5,Uncertainty score_5,Number Comprehension score_5,Graph Comprehension score_5,Calculation score_4,Total Score_19
0,1,2,2,2,2,2,1,4,1,1,1,1,3,25,20,3,500,10,0.10,1,1,1,1,1,1,1,1,0,1,1,1,0,1,1,1,1,1,1,1,5,2,3,3,4,17
1,2,1,1,1,1,2,2,4,2,1,1,1,1,50,20,3,500,10,0.10,1,0,0,0,0,1,0,1,1,1,1,1,0,0,1,1,1,1,1,1,1,1,4,2,4,12
2,5,2,2,1,2,2,2,4,1,1,1,2,2,20,60,3,500,100,1.00,3,1,1,0,1,1,0,1,0,1,1,0,0,0,0,1,1,0,0,0,4,1,2,1,1,9
3,8,1,1,1,1,2,3,4,2,1,1,2,2,25,20,3,400,10,0.10,2,0,0,0,0,1,0,1,1,1,1,0,0,1,1,1,0,1,1,0,1,1,3,3,2,10
4,9,2,1,1,2,2,4,4,2,1,1,1,4,25,20,3,500,10,0.10,3,1,0,0,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,0,3,1,5,3,3,15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3901,15636,1,1,1,1,2,3,2,1,2,1,1,1,40,60,4,500,200,10.00,2,0,0,0,0,1,0,0,0,0,1,1,0,0,0,0,1,0,0,0,1,0,2,0,1,4
3902,15717,1,2,1,1,2,4,4,2,1,1,3,2,25,20,3,500,10,0.10,2,0,1,0,0,1,0,1,1,1,1,0,0,1,1,1,1,1,1,0,2,1,3,3,3,12
3903,15788,1,1,1,2,2,3,4,2,1,1,4,4,25,10,3,450,50,0.01,2,0,0,0,1,1,0,1,1,1,1,0,1,1,0,1,0,0,0,0,2,1,4,2,0,9
3904,15843,1,1,1,1,2,2,4,2,1,1,2,3,25,20,3,500,1,0.10,3,0,0,0,0,1,0,1,1,1,1,0,0,1,1,1,1,0,1,0,1,1,3,3,2,10
3905,15861,1,1,1,2,2,2,4,2,1,2,4,4,30,20,4,600,1,1.00,3,0,0,0,1,1,0,1,1,1,0,0,1,0,1,0,0,0,0,0,2,1,3,1,0,7

In [4]:
fiveCountries = pd.concat([otherCountries,india])

In [5]:
fiveCountries = fiveCountries.reset_index().rename({"index":"randomizerid"}, axis = 1)
fiveCountries

,randomizerid,responseid,q8_2_1,q8_2_2,q8_2_3,q8_2_4,q8_2_5,q8_3,q8_4,q8_5berlin_1,q8_5london_1,q8_5paris_1,q8_6,q8_7,q9_1_1,q9_2_1,q9_3,q10_1_1,q10_2_1,q10_3_1,q10_4,certainty1,certainty2,certainty3,certainty4,certainty5,uncertainty1,uncertainty2,numeracy1,numeracy2,numeracy3,numeracy4,numeracy5,graph1,graph2,graph3,riskcalculation1,riskcalculation2,riskcalculation3,riskcalculation4,Certainty score_5,Uncertainty score_5,Number Comprehension score_5,Graph Comprehension score_5,Calculation score_4,Total Score_19,#,Unnamed: 1,#.1,Please indicate your Gender.,Please mark your age (in years),What is currently your highest Education?,Please state your current occupation.,How do you describe your willingness to take financial risk in general?,"Given the number of years that you have held various investments and the amount of investing you might have done, what degree of investment experience in the stock market do you have?","If an expert tries to worry or scare me, i.e. a financial advisor about my financial situation, I choose another expert.",I only buy a financial product I understand.,I trust doctors.,"When I want to buy a bigger item like a refrigerator or an expensive item of clothing, I wait a month to see whether I still want it and only buy it then.",I always keep in mind that everything I do on the web could be used to my disadvantage.,"In my household, we/I spend:","In my household, we/I",_Distribution 1_\n\nHow risky do you perceive the investment to be?,_Distribution 2_\n\nHow risky do you perceive the investment to be?,_Distribution 3_\n\nHow risky do you perceive the investment to be?,_Distribution 4_\n\nHow risky do you perceive the investment to be?,_Distribution 5_\n\nHow risky do you perceive the investment to be?,Distribution 6\n\nHow risky do you perceive the investment to be?,Distribution 7\n\nHow risky do you perceive the investment to be?,Distribution 8\n\nHow risky do you perceive the investment to be?,*Mumbai * A = 9 out of 10000 *OR * B = 1 out of 1000,*Bengaluru * A = 0.7% *OR * B = 0.099%,*Kolkata * A = 0.61% *OR * B = 6 out of 10000,HIV test,Fingerprint,DNA test,Cancer screening test,Professional horoscope,A study estimates that eating 100g chocolate everyday increases the risk of obesity by 20%. Which of the following statements is true?,There is an official prediction that the national stock market will grow 2% annually over the next 5 years. This means thatâ€¦,Imagine you are told that the price of the stock Soya Ruchi increases from INR 60 to INR 120 after the company merger. What does this mean?,It is predicted that Indigo Bank has 30% chance of default next year. Which of the following alternatives is the most appropriate interpretation of the statement?,"The probability that the economy will go into a recession this year is 30%. If the economy goes into recession, the probability that the stock market will decrease is 80%. If the economy does not go into a recession, the probability that the stock market will decrease is 23%. What is the probability that the economy goes into recession given that the stock market decreased?",A new policy intervention increases the number of people who are employed by 20%. This statistic implies that the intervention increases the number of people who are employed from:,"Imagine you are told that a new medication increases the number of people who recover from a disease from 2 out of 1,000 to 4 out of 1,000. This implies:","Imagine that we flip a fair coin 1,000 times. What is your best guess about how many times the coin will come up heads in 1,000 flips? \n\n\_\_\_\_\_\_ times out of 1,000.","In the Bingo Lottery, the chance of winning a $10 prize is 1%. What is your best guess about how many people will win a $10 prize if 1,000 people each buy a single ticket for Bingo Lottery?\n\n\_\_\_\_\_\_ person(s) out of 1,000.","In a sweepstakes, the chance of winning a car is 1 in 1,000. What percentage of tickets for the sweepstakes wins a car?\n\n\_\_\_\_\_ % of tickets","About 10 out of 1,000 children develop Down syndrome. In a Down syndrome test, 9 out of these 10 children with Down syndrome tested positive. Out of the 990 children without Down syndrome 50 nevertheless tested positive. Among those women with a positive test result concerning their child how many actually have a child with Down syndrome? [Select one response only]","Approximately what percentage (%) of people who die from cancer die from colon cancer, breast cancer, and prostate cancer taken together?",The following figure shows the number of men and women among a group of smartphone users. The total number of circles is 100. \n\nHow many more men than women are there among the 100 people using a smartphone?,"In a magazine you see two advertisements, one on page 5 and another on page 12. Each is for a different drug for treating heart disease, and each includes a graph showing the effectiveness of the drug compared to a placebo (sugar pill).\n\nCompared to the placebo, which treatment leads to a larger decrease in the percentage of patients who die?",Please indicate your approximate annual personal income from all sources for last year,"Please provide a rough guess (in Indian Rupees) of the worth of your household's assets. Please do not forget to correct it for your debts, such as a mortgage or any loans you might have.",uid,Response Type,Start Date (UTC),Stage Date (UTC),Submit Date (UTC),Network ID,LTA
0,0,1.0,2,2,2,2,2,1,4,1,1,1,1,3,25,20,3,500,10,0.1,1,1,1,1,1,1,1,1,0,1,1,1,0,1,1,1,1,1,1,1,5,2,3,3,4,17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,2.0,1,1,1,1,2,2,4,2,1,1,1,1,50,20,3,500,10,0.1,1,0,0,0,0,1,0,1,1,1,1,1,0,0,1,1,1,1,1,1,1,1,4,2,4,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,5.0,2,2,1,2,2,2,4,1,1,1,2,2,20,60,3,500,100,1.0,3,1,1,0,1,1,0,1,0,1,1,0,0,0,0,1,1,0,0,0,4,1,2,1,1,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,8.0,1,1,1,1,2,3,4,2,1,1,2,2,25,20,3,400,10,0.1,2,0,0,0,0,1,0,1,1,1,1,0,0,1,1,1,0,1,1,0,1,1,3,3,2,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,9.0,2,1,1,2,2,4,4,2,1,1,1,4,25,20,3,500,10,0.1,3,1,0,0,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,0,3,1,5,3,3,15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4544,638,NaN,2,1,2,2,2,2,2,2,1,1,1,3,50,40,1,500,100,1.0,3,1,0,1,1,1,0,0,1,1,1,1,0,0,0,0,1,0,0,0,4,0,4,0,1,9,zeoufbqlngfunzzeoymhtj2sp5cw6lur,396.0,zeoufbqlngfunzzeoymhtj2sp5cw6lur,Male,25 - 35,Post Graduate,"Investment Professional, i.e. stock broker/tra...",3.0,8.0,Not at all,Somewhat,Somewhat,Moderately,Somewhat,less than half of the household income and sav...,"spend as it feel right, and do not have an eme...",3.0,4.0,4.0,3.0,6.0,6.0,3.0,4.0,B,A,A,No,Yes,No,No,No,"The higher the quality of the study, the more ...",the growth rate over five years will be exactl...,the stock price increased by 100%,Banks similar to Indigo will default 30% of th...,50%,70 in 100 people prior to the intervention to ...,The medication increases recovery by 100%,500.0,100.0,1.0,59 out of 1000,50.0,40.0,Crosicol,"&lt; 5,00,000",50000.0,MXFoD1725258821KAh,completed,2024-09-02 06:36:01,NaN,2024-09-02 06:46:38,c31fa70c8d,7.372685
4545,639,NaN,2,1,1,2,2,4,3,2,1,1,1,2,25,20,4,500,10,1.0,3,1,0,0,1,1,0,0,1,1,1,1,0,1,1,0,1,1,0,0,3,0,4,2,2,11,zfemo30rg0ekva18x1kjwzfemo2wpg2p,185.0,zfemo30rg0ekva18x1kjwzfemo2wpg2p,Male,36 - 45,Ph.D. or higher,Employee/Consultant in Other than the Finance ...,6.0,8.0,Not at all,Moderately,Just about,Not at all,Not at all,less than half of the household income and sav...,"have an emergency fund, and spend as it feels ...",3.0,1.0,4.0,2.0,0.0,5.0,0.0,2.0,B,A,A,No,Yes,Yes,No,No,"Irrespective of the quality of the study, futu...",the growth rate over five years will be betwee...,the stock price increased by 100%,30% of central bankers think that Indigo Bank ...,30%,"100 in 10,000 people prior to the intervention...",The medication increases recovery by 100%,500.0,10.0,1.0,59 out of 1000,25.0,20.0,Canâ€™t say,"15,00,001 - 25,00,000",8500000.0,MXUxt1725260651heG,completed,2024-09-02 07:08:18,NaN,2024-09-02 07:23:09,fbb956cffc,10.312500
4546,640,NaN,1,1,1,2,2,3,4,2,2,2,3,4,25,20,2,500,10,1.0,1,0,0,0,1,1,0,1,1,0,0,0,1,1,1,0,1,1,0,1,2,1,2,2,3,10,znqvw4t38br3072znqvwvjsgb6wvj7nt,305.0,znqvw4t38br3072znqvwvjsgb6wvj7nt,Female,36 - 45,Post Graduate,Entrepreneur or Own Business,5.0,5.0,Somewhat,Completely,Just about,Moderately,Somewhat,less than half of the household income and sav...,"spend as it feel right, and do not have an eme...",0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,B,B,B,Yes,Yes,Yes,No,No,"Irrespective of the quality of the study, futu...",it is not possible to predict the growth rate ...,the stock price increased by 50%,30% of the banks customers will default next year,80%,it is not possible to determine which of the a...,The medication increases recovery by 2%,500.0,10.0,1.0,9 out of 59,25.0,20.0,Hertinol,"5,00,000 - 15,00,000",2000000.0,MXd921725259652XDJ,completed,2024-09-02 06:49:56,NaN,2024-09-02 07:17:20,1964f49e1c,19.027778
4547,641,NaN,2,1,1,2,2,2,3,1,1,2,4,1,50,10,3,750,10,1.0,3,1,0,0,1,1,0,0,0,1,0,0,0,0,0,1,0,1,0,0,3,0,1,1,1,6,zstpq23h1x3ilab8s8vsrbkw8t4zstpq,306.0,zstpq23h1x3ilab8s8vsrbkw8t4zstpq,Male,18 - 25,Under Graduate,Entrepreneur or Own Business,6.0,9.0,Completely,Completely,Moderately,Completely,Moderately,"all or more than our household income, because...","have an emergency fund, and spend as it feels ...",6.0,3.0,7.0,1.0,2.0,7.0,7.0,3.0,A,A,B,No,Yes,Yes,No,No,"The higher the quality of the study, the more ...",the growth rate over five years will be betwee...,the stock price increased by 60%,Banks similar to Indigo will default 30% of th...,80%,5 in 100 people prior to the intervention to 6...,None of the above is implied.,750.0,10.0,1.0,59 out of 1000,50.0,10.0,They are equal,"5,00,000 - 15,00,000",60000000.0,MXfmg1725259705Fkj,completed,2024-09-02 06:49:52,NaN,2024-09-02 07:01:04,03aa77ec48,7.777778
4548,642,NaN,2,1,1,1,1,2,4,2,1,1,3,1,25,60,4,500,10,1.0,3,1,0,0,0,0,0,1,1,1,1,0,0,1,0,0,1,1,0,0,1,1,3,1,2,8,ztfdlcbiyo1xco3ztfdl4ozqpte2q3m9,95.0,ztfdlcbiyo1xco3ztfdl4ozqpte2q3m9,Male,25 - 35,Post Graduate,Entrepreneur or Own Business,6.0,7.0,Somewhat,Just about,Completely,Moderately,Somewhat,more than half of the household income and sav...,"spend as it feel right, and do not have an eme...",6.0,0.0,2.0,5.0,3.0,7.0,0.0,4.0,B,A,A,No,Yes,Yes,Yes,Yes,"The higher the quality of the study, the more ...",it is not possible to predict the growth rate ...,the stock price increased by 100%,30% of central bankers think that Indigo Bank ...,80%,5 in 100 people prior to the intervention to 6...,The medication increases recovery by 2%,500.0,10.0,1.0,59 out of 1000,25.0,60.0,Canâ€™t say,"15,00,001 - 25,00,000",5000000.0,MXjp51725955476hMt,completed,2024-09-10 08:06:34,NaN,2024-09-10 08:16:35,f68294192e,6.956019

In [6]:
fiveCountriesSample50_1 = fiveCountries.sample(frac = 0.5, replace = False).copy()
fiveCountriesSample50_1.sort_values(by = ["randomizerid"])

,randomizerid,responseid,q8_2_1,q8_2_2,q8_2_3,q8_2_4,q8_2_5,q8_3,q8_4,q8_5berlin_1,q8_5london_1,q8_5paris_1,q8_6,q8_7,q9_1_1,q9_2_1,q9_3,q10_1_1,q10_2_1,q10_3_1,q10_4,certainty1,certainty2,certainty3,certainty4,certainty5,uncertainty1,uncertainty2,numeracy1,numeracy2,numeracy3,numeracy4,numeracy5,graph1,graph2,graph3,riskcalculation1,riskcalculation2,riskcalculation3,riskcalculation4,Certainty score_5,Uncertainty score_5,Number Comprehension score_5,Graph Comprehension score_5,Calculation score_4,Total Score_19,#,Unnamed: 1,#.1,Please indicate your Gender.,Please mark your age (in years),What is currently your highest Education?,Please state your current occupation.,How do you describe your willingness to take financial risk in general?,"Given the number of years that you have held various investments and the amount of investing you might have done, what degree of investment experience in the stock market do you have?","If an expert tries to worry or scare me, i.e. a financial advisor about my financial situation, I choose another expert.",I only buy a financial product I understand.,I trust doctors.,"When I want to buy a bigger item like a refrigerator or an expensive item of clothing, I wait a month to see whether I still want it and only buy it then.",I always keep in mind that everything I do on the web could be used to my disadvantage.,"In my household, we/I spend:","In my household, we/I",_Distribution 1_\n\nHow risky do you perceive the investment to be?,_Distribution 2_\n\nHow risky do you perceive the investment to be?,_Distribution 3_\n\nHow risky do you perceive the investment to be?,_Distribution 4_\n\nHow risky do you perceive the investment to be?,_Distribution 5_\n\nHow risky do you perceive the investment to be?,Distribution 6\n\nHow risky do you perceive the investment to be?,Distribution 7\n\nHow risky do you perceive the investment to be?,Distribution 8\n\nHow risky do you perceive the investment to be?,*Mumbai * A = 9 out of 10000 *OR * B = 1 out of 1000,*Bengaluru * A = 0.7% *OR * B = 0.099%,*Kolkata * A = 0.61% *OR * B = 6 out of 10000,HIV test,Fingerprint,DNA test,Cancer screening test,Professional horoscope,A study estimates that eating 100g chocolate everyday increases the risk of obesity by 20%. Which of the following statements is true?,There is an official prediction that the national stock market will grow 2% annually over the next 5 years. This means thatâ€¦,Imagine you are told that the price of the stock Soya Ruchi increases from INR 60 to INR 120 after the company merger. What does this mean?,It is predicted that Indigo Bank has 30% chance of default next year. Which of the following alternatives is the most appropriate interpretation of the statement?,"The probability that the economy will go into a recession this year is 30%. If the economy goes into recession, the probability that the stock market will decrease is 80%. If the economy does not go into a recession, the probability that the stock market will decrease is 23%. What is the probability that the economy goes into recession given that the stock market decreased?",A new policy intervention increases the number of people who are employed by 20%. This statistic implies that the intervention increases the number of people who are employed from:,"Imagine you are told that a new medication increases the number of people who recover from a disease from 2 out of 1,000 to 4 out of 1,000. This implies:","Imagine that we flip a fair coin 1,000 times. What is your best guess about how many times the coin will come up heads in 1,000 flips? \n\n\_\_\_\_\_\_ times out of 1,000.","In the Bingo Lottery, the chance of winning a $10 prize is 1%. What is your best guess about how many people will win a $10 prize if 1,000 people each buy a single ticket for Bingo Lottery?\n\n\_\_\_\_\_\_ person(s) out of 1,000.","In a sweepstakes, the chance of winning a car is 1 in 1,000. What percentage of tickets for the sweepstakes wins a car?\n\n\_\_\_\_\_ % of tickets","About 10 out of 1,000 children develop Down syndrome. In a Down syndrome test, 9 out of these 10 children with Down syndrome tested positive. Out of the 990 children without Down syndrome 50 nevertheless tested positive. Among those women with a positive test result concerning their child how many actually have a child with Down syndrome? [Select one response only]","Approximately what percentage (%) of people who die from cancer die from colon cancer, breast cancer, and prostate cancer taken together?",The following figure shows the number of men and women among a group of smartphone users. The total number of circles is 100. \n\nHow many more men than women are there among the 100 people using a smartphone?,"In a magazine you see two advertisements, one on page 5 and another on page 12. Each is for a different drug for treating heart disease, and each includes a graph showing the effectiveness of the drug compared to a placebo (sugar pill).\n\nCompared to the placebo, which treatment leads to a larger decrease in the percentage of patients who die?",Please indicate your approximate annual personal income from all sources for last year,"Please provide a rough guess (in Indian Rupees) of the worth of your household's assets. Please do not forget to correct it for your debts, such as a mortgage or any loans you might have.",uid,Response Type,Start Date (UTC),Stage Date (UTC),Submit Date (UTC),Network ID,LTA
3908,2,NaN,1,1,2,1,1,1,2,1,2,2,1,3,79,40,2,46,100,99.0,3,0,0,1,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,1,1,1,0,0,3,01ro2iftnum5v4cn01r03c75aa24emhq,528.0,01ro2iftnum5v4cn01r03c75aa24emhq,Female,18 - 25,Under Graduate,Student,5.0,8.0,Just about,Completely,Completely,Completely,Just about,more than half of the household income and sav...,"write down budget and spending, and have an em...",6.0,6.0,2.0,6.0,6.0,6.0,2.0,4.0,A,B,B,Yes,Yes,No,Yes,Yes,"The lower the quality of the study, the more l...",the growth rate over five years will be exactl...,an answer is not possible based on the informa...,Banks similar to Indigo will default 30% of th...,50%,70 in 100 people prior to the intervention to ...,The medication increases recovery by 100%,46.0,100.0,99.0,59 out of 1000,79.0,40.0,Hertinol,"5,00,000 - 15,00,000",500000.0,MX7wI1724844822zNm,completed,2024-08-28 11:36:50,NaN,2024-08-28 11:51:07,81a8a6836a,9.918981
3909,3,NaN,1,1,1,2,2,1,1,2,1,2,3,1,17,65,3,500,1,1.0,3,0,0,0,1,1,1,0,1,1,0,0,0,0,0,1,1,0,0,0,2,1,2,1,1,7,022xoawhrghfhv4a1g022xmz7hb0m41f,442.0,022xoawhrghfhv4a1g022xmz7hb0m41f,Female,46 - 55,Under Graduate,Entrepreneur or Own Business,5.0,4.0,Somewhat,Somewhat,Moderately,Just about,Somewhat,"all or more than the household income, even th...","spend as it feel right, and do not have an eme...",4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,B,A,B,Yes,Yes,Yes,No,No,"The lower the quality of the study, the more l...",the growth rate will be 0.4% on average each year,the stock price increased by 60%,30% of the banks customers will default next year,80%,5 in 100 people prior to the intervention to 6...,The medication increases recovery by 2%,500.0,1.0,1.0,59 out of 1000,17.0,65.0,They are equal,"&lt; 5,00,000",15000000.0,MXFDH1725178659xRn,completed,2024-09-01 08:21:14,NaN,2024-09-01 08:33:49,fbd8962401,8.738426
4,4,9.0,2,1,1,2,2,4,4,2,1,1,1,4,25,20,3,500,10,0.1,3,1,0,0,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,0,3,1,5,3,3,15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3911,5,NaN,2,2,1,2,2,3,4,1,2,1,4,3,50,20,2,1000,1,10.0,1,1,1,0,1,1,0,1,0,0,1,0,0,0,1,0,0,0,0,1,4,1,1,1,1,8,037aefjdt26mnjd102nz0pk037aedfhc,544.0,037aefjdt26mnjd102nz0pk037aedfhc,Male,46 - 55,Post Graduate,Employee/Consultant in Other than the Finance ...,3.0,6.0,Somewhat,Somewhat,Somewhat,Somewhat,Somewhat,more than half of the household income and sav...,"write down budget and spending, but have no em...",3.0,1.0,6.0,1.0,2.0,6.0,7.0,5.0,A,B,A,No,No,Yes,No,No,"Irrespective of the quality of the study, futu...",it is not possible to predict the growth rate ...,an answer is not possible based on the informa...,Banks similar to Indigo will default 30% of th...,60%,70 in 100 people prior to the intervention to ...,None of the above is implied.,1000.0,1.0,10.0,9 out of 59,50.0,20.0,Hertinol,"5,00,000 - 15,00,000",7000000.0,MXpv61724844846UVs,completed,2024-08-28 11:35:50,NaN,2024-08-28 11:45:54,f51b723011,6.990741
5,5,10.0,1,1,1,2,2,3,4,2,1,1,2,3,50,20,3,600,10,0.1,2,0,0,0,1,1,0,1,1,1,1,0,0,0,1,1,0,1,1,0,2,1,3,2,2,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3893,3893,14328.0,1,1,2,1,2,2,4,2,1,1,1,1,25,60,3,600,10,0.1,1,0,0,1,0,1,0,1,1,1,1,1,0,1,0,1,0,1,1,1,2,1,4,2,3,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3898,3898,14419.0,1,1,1,1,2,3,3,2,2,2,1,1,30,20,3,500,10,1.0,3,0,0,0,0,1,0,0,1,0,0,1,0,0,1,1,1,1,0,0,1,0,2,2,2,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3899,3899,14448.0,2,2,2,2,2,2,2,2,1,2,3,3,20,20,2,20,20,5.0,2,1,1,1,1,1,0,0,1,1,0,0,0,0,1,0,0,0,0,0,5,0,2,1,0,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3902,3902,15717.0,1,2,1,1,2,4,4,2,1,1,3,2,25,20,3,500,10,0.1,2,0,1,0,0,1,0,1,1,1,1,0,0,1,1,1,1,1,1,0,2,1,3,3,3,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3904,3904,15843.0,1,1,1,1,2,2,4,2,1,1,2,3,25,20,3,500,1,0.1,3,0,0,0,0,1,0,1,1,1,1,0,0,1,1,1,1,0,1,0,1,1,3,3,2,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
fiveCountriesSample50_2 = fiveCountries.loc[ ~fiveCountries.index.isin(fiveCountriesSample50_1.index) ]

In [8]:
fiveCountriesSample50_2.sort_values(by = ["randomizerid"])

,randomizerid,responseid,q8_2_1,q8_2_2,q8_2_3,q8_2_4,q8_2_5,q8_3,q8_4,q8_5berlin_1,q8_5london_1,q8_5paris_1,q8_6,q8_7,q9_1_1,q9_2_1,q9_3,q10_1_1,q10_2_1,q10_3_1,q10_4,certainty1,certainty2,certainty3,certainty4,certainty5,uncertainty1,uncertainty2,numeracy1,numeracy2,numeracy3,numeracy4,numeracy5,graph1,graph2,graph3,riskcalculation1,riskcalculation2,riskcalculation3,riskcalculation4,Certainty score_5,Uncertainty score_5,Number Comprehension score_5,Graph Comprehension score_5,Calculation score_4,Total Score_19,#,Unnamed: 1,#.1,Please indicate your Gender.,Please mark your age (in years),What is currently your highest Education?,Please state your current occupation.,How do you describe your willingness to take financial risk in general?,"Given the number of years that you have held various investments and the amount of investing you might have done, what degree of investment experience in the stock market do you have?","If an expert tries to worry or scare me, i.e. a financial advisor about my financial situation, I choose another expert.",I only buy a financial product I understand.,I trust doctors.,"When I want to buy a bigger item like a refrigerator or an expensive item of clothing, I wait a month to see whether I still want it and only buy it then.",I always keep in mind that everything I do on the web could be used to my disadvantage.,"In my household, we/I spend:","In my household, we/I",_Distribution 1_\n\nHow risky do you perceive the investment to be?,_Distribution 2_\n\nHow risky do you perceive the investment to be?,_Distribution 3_\n\nHow risky do you perceive the investment to be?,_Distribution 4_\n\nHow risky do you perceive the investment to be?,_Distribution 5_\n\nHow risky do you perceive the investment to be?,Distribution 6\n\nHow risky do you perceive the investment to be?,Distribution 7\n\nHow risky do you perceive the investment to be?,Distribution 8\n\nHow risky do you perceive the investment to be?,*Mumbai * A = 9 out of 10000 *OR * B = 1 out of 1000,*Bengaluru * A = 0.7% *OR * B = 0.099%,*Kolkata * A = 0.61% *OR * B = 6 out of 10000,HIV test,Fingerprint,DNA test,Cancer screening test,Professional horoscope,A study estimates that eating 100g chocolate everyday increases the risk of obesity by 20%. Which of the following statements is true?,There is an official prediction that the national stock market will grow 2% annually over the next 5 years. This means thatâ€¦,Imagine you are told that the price of the stock Soya Ruchi increases from INR 60 to INR 120 after the company merger. What does this mean?,It is predicted that Indigo Bank has 30% chance of default next year. Which of the following alternatives is the most appropriate interpretation of the statement?,"The probability that the economy will go into a recession this year is 30%. If the economy goes into recession, the probability that the stock market will decrease is 80%. If the economy does not go into a recession, the probability that the stock market will decrease is 23%. What is the probability that the economy goes into recession given that the stock market decreased?",A new policy intervention increases the number of people who are employed by 20%. This statistic implies that the intervention increases the number of people who are employed from:,"Imagine you are told that a new medication increases the number of people who recover from a disease from 2 out of 1,000 to 4 out of 1,000. This implies:","Imagine that we flip a fair coin 1,000 times. What is your best guess about how many times the coin will come up heads in 1,000 flips? \n\n\_\_\_\_\_\_ times out of 1,000.","In the Bingo Lottery, the chance of winning a $10 prize is 1%. What is your best guess about how many people will win a $10 prize if 1,000 people each buy a single ticket for Bingo Lottery?\n\n\_\_\_\_\_\_ person(s) out of 1,000.","In a sweepstakes, the chance of winning a car is 1 in 1,000. What percentage of tickets for the sweepstakes wins a car?\n\n\_\_\_\_\_ % of tickets","About 10 out of 1,000 children develop Down syndrome. In a Down syndrome test, 9 out of these 10 children with Down syndrome tested positive. Out of the 990 children without Down syndrome 50 nevertheless tested positive. Among those women with a positive test result concerning their child how many actually have a child with Down syndrome? [Select one response only]","Approximately what percentage (%) of people who die from cancer die from colon cancer, breast cancer, and prostate cancer taken together?",The following figure shows the number of men and women among a group of smartphone users. The total number of circles is 100. \n\nHow many more men than women are there among the 100 people using a smartphone?,"In a magazine you see two advertisements, one on page 5 and another on page 12. Each is for a different drug for treating heart disease, and each includes a graph showing the effectiveness of the drug compared to a placebo (sugar pill).\n\nCompared to the placebo, which treatment leads to a larger decrease in the percentage of patients who die?",Please indicate your approximate annual personal income from all sources for last year,"Please provide a rough guess (in Indian Rupees) of the worth of your household's assets. Please do not forget to correct it for your debts, such as a mortgage or any loans you might have.",uid,Response Type,Start Date (UTC),Stage Date (UTC),Submit Date (UTC),Network ID,LTA
0,0,1.0,2,2,2,2,2,1,4,1,1,1,1,3,25,20,3,500,10,0.10,1,1,1,1,1,1,1,1,0,1,1,1,0,1,1,1,1,1,1,1,5,2,3,3,4,17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3906,0,NaN,1,1,1,1,1,1,1,1,2,1,2,4,40,60,3,30,20,30.00,2,0,0,0,0,0,1,0,0,0,1,0,1,0,0,1,0,0,0,0,0,1,2,1,0,4,00dn8csjzlekx6gzhrcv00dn8csj32tz,547.0,00dn8csjzlekx6gzhrcv00dn8csj32tz,Male,25 - 35,Under Graduate,"Investment Professional, i.e. stock broker/tra...",7.0,10.0,Completely,Just about,Completely,Completely,Just about,"all or more than the household income, even th...","have an emergency fund, and spend as it feels ...",7.0,7.0,7.0,6.0,6.0,6.0,6.0,7.0,A,B,A,Yes,Yes,Yes,Yes,Yes,"The lower the quality of the study, the more l...",the growth rate will be 0.4% on average each year,the stock price increased by 50%,30% of the banks customers will default next year,30%,it is not possible to determine which of the a...,The medication increases recovery by 50%,30.0,20.0,30.0,9 out of 10,40.0,60.0,They are equal,"5,00,000 - 15,00,000",50000.0,MX9oX1724844773oYI,completed,2024-08-28 11:35:35,NaN,2024-08-28 12:02:05,f30fdd629e,18.402778
3907,1,NaN,1,1,1,1,2,2,3,2,2,1,2,2,50,10,3,500,100,1.00,3,0,0,0,0,1,0,0,1,0,1,0,0,0,0,1,1,0,0,0,1,0,2,1,1,5,00ujdxbfoya0donu8r00ujcjdkojc99x,428.0,00ujdxbfoya0donu8r00ujcjdkojc99x,Female,25 - 35,Under Graduate,Employee/Consultant in Other than the Finance ...,7.0,8.0,Completely,Completely,Completely,Moderately,Moderately,less than half of the household income and sav...,"write down budget and spending, and have an em...",2.0,1.0,1.0,1.0,0.0,2.0,0.0,0.0,B,B,A,Yes,Yes,Yes,Yes,No,"The higher the quality of the study, the more ...",the growth rate over five years will be betwee...,the stock price increased by 50%,The bank will default on 30% of repayments in ...,50%,"100 in 10,000 people prior to the intervention...",The medication increases recovery by 50%,500.0,100.0,1.0,59 out of 1000,50.0,10.0,They are equal,"&lt; 5,00,000",1500000.0,MXic21725178744djB,completed,2024-09-01 08:23:04,NaN,2024-09-01 09:24:44,1c1d51349c,42.824074
1,1,2.0,1,1,1,1,2,2,4,2,1,1,1,1,50,20,3,500,10,0.10,1,0,0,0,0,1,0,1,1,1,1,1,0,0,1,1,1,1,1,1,1,1,4,2,4,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,5.0,2,2,1,2,2,2,4,1,1,1,2,2,20,60,3,500,100,1.00,3,1,1,0,1,1,0,1,0,1,1,0,0,0,0,1,1,0,0,0,4,1,2,1,1,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3897,3897,14396.0,1,1,1,1,2,2,4,1,1,1,1,2,8,20,3,500,10,0.10,2,0,0,0,0,1,0,1,0,1,1,1,0,0,1,1,1,1,1,0,1,1,3,2,3,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3900,3900,15573.0,1,1,1,1,2,1,2,2,2,2,4,4,25,20,3,500,10,0.10,3,0,0,0,0,1,1,0,1,0,0,0,1,1,1,1,1,1,1,0,1,1,2,3,3,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3901,3901,15636.0,1,1,1,1,2,3,2,1,2,1,1,1,40,60,4,500,200,10.00,2,0,0,0,0,1,0,0,0,0,1,1,0,0,0,0,1,0,0,0,1,0,2,0,1,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3903,3903,15788.0,1,1,1,2,2,3,4,2,1,1,4,4,25,10,3,450,50,0.01,2,0,0,0,1,1,0,1,1,1,1,0,1,1,0,1,0,0,0,0,2,1,4,2,0,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3905,3905,15861.0,1,1,1,2,2,2,4,2,1,2,4,4,30,20,4,600,1,1.00,3,0,0,0,1,1,0,1,1,1,0,0,1,0,1,0,0,0,0,0,2,1,3,1,0,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
fiveCountriesSample50_1.to_csv("5_india_riskliteracy_2024_sample1.csv")

In [10]:
fiveCountriesSample50_2.to_csv("5_india_riskliteracy_2024_sample2.csv")

In [11]:
fiveCountries.to_csv("5_india_riskliteracy_2024.csv")